services:
  - type: web
    name: cgpa-calc-backend
    env: node
    buildCommand: npm install --production
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        value: mongodb+srv://babutmuthumari_db_user:Blackpanda79@cluster0.weaiuxh.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - key: JWT_SECRET
        value: 090d241d5149530d3c702a9cbb291f54ca40d49a2e0a650c9237e5f2567df79db197cdab31f95adac94b3bfa41661300835a62ebda8908dd4e8f1f3dd117a03f
      - key: FRONTEND_URL
        value: https://cgpa-calculator-aroj.vercel.app
