services:
  - type: web
    name: cgpa-calc-backend
    env: node
    buildCommand: npm install --production
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        value: mongodb+srv://babutmuthumari_db_user:Blackpanda79@cluster0.weaiuxh.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - key: JWT_SECRET
        value: 95db73f0cd88343fd7b110d9b1d73886f19f8391fbda6cfbb58c47901833f182
      - key: FRONTEND_URL
        value: https://cgpa-calculator-aroj.vercel.app
